// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrkUuc8jtOJHu0tCytnrGIEX7mUUdZP3A',
    appId: '1:73642971836:web:461364ddbd16ca626d76b9',
    messagingSenderId: '73642971836',
    projectId: 'fhc-pic-sys',
    authDomain: 'fhc-pic-sys.firebaseapp.com',
    storageBucket: 'fhc-pic-sys.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7FnHezkMnp0mhsD-_X2In1EtPkk8epY',
    appId: '1:73642971836:android:dd4c5562d865b9e26d76b9',
    messagingSenderId: '73642971836',
    projectId: 'fhc-pic-sys',
    storageBucket: 'fhc-pic-sys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYtEqWRTdQ7d5KtSTf9qqGXuosxALPRQ',
    appId: '1:73642971836:ios:9bd32248be40e4e76d76b9',
    messagingSenderId: '73642971836',
    projectId: 'fhc-pic-sys',
    storageBucket: 'fhc-pic-sys.appspot.com',
    iosClientId: '73642971836-evspfj57rnmf6om9gejereohv6h33ot1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALYtEqWRTdQ7d5KtSTf9qqGXuosxALPRQ',
    appId: '1:73642971836:ios:9bd32248be40e4e76d76b9',
    messagingSenderId: '73642971836',
    projectId: 'fhc-pic-sys',
    storageBucket: 'fhc-pic-sys.appspot.com',
    iosClientId: '73642971836-evspfj57rnmf6om9gejereohv6h33ot1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
